"""Initial database schema based on models

Revision ID: eb8c6722d954
Revises: 
Create Date: 2025-04-21 16:07:56.388689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb8c6722d954'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('session_file', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('target_chats',
    sa.Column('internal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('access_hash', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('internal_id'),
    sa.UniqueConstraint('chat_id', name='uq_target_chats_chat_id')
    )
    op.create_index(op.f('ix_target_chats_chat_id'), 'target_chats', ['chat_id'], unique=True)
    op.create_index(op.f('ix_target_chats_status'), 'target_chats', ['status'], unique=False)
    op.create_index(op.f('ix_target_chats_username'), 'target_chats', ['username'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('access_hash', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('is_contact', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.Column('is_scam', sa.Boolean(), nullable=False),
    sa.Column('is_fake', sa.Boolean(), nullable=False),
    sa.Column('lang_code', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_type', sa.Text(), nullable=True),
    sa.Column('inviter_user_id', sa.BigInteger(), nullable=True),
    sa.Column('joined_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['target_chats.chat_id'], ),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_chat_participant')
    )
    op.create_index('ix_chat_participants_chat_id', 'chat_participants', ['chat_id'], unique=False)
    op.create_index('ix_chat_participants_user_id', 'chat_participants', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('message_type', sa.Text(), nullable=False),
    sa.Column('media_path', sa.Text(), nullable=True),
    sa.Column('media_type', sa.Text(), nullable=True),
    sa.Column('reply_to_msg_id', sa.BigInteger(), nullable=True),
    sa.Column('forwarded_from_id', sa.BigInteger(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('forwards', sa.Integer(), nullable=True),
    sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['target_chats.chat_id'], ),
    sa.ForeignKeyConstraint(['forwarded_from_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'chat_id', name='uq_message_id_chat_id')
    )
    op.create_index('ix_messages_chat_id_date', 'messages', ['chat_id', 'date'], unique=False)
    op.create_index(op.f('ix_messages_date'), 'messages', ['date'], unique=False)
    op.create_index(op.f('ix_messages_message_type'), 'messages', ['message_type'], unique=False)
    op.create_index('ix_messages_user_id', 'messages', ['user_id'], unique=False)
    op.create_table('private_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=True),
    sa.Column('media_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_messages_date'), 'private_messages', ['date'], unique=False)
    op.create_index('ix_private_messages_dialog_date', 'private_messages', ['from_user_id', 'to_user_id', 'date'], unique=False)
    op.create_table('user_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('contact_user_id', sa.BigInteger(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'contact_user_id', name='uq_user_contact_link'),
    sa.UniqueConstraint('owner_user_id', 'phone', name='uq_user_contact_phone')
    )
    op.create_index(op.f('ix_user_contacts_contact_user_id'), 'user_contacts', ['contact_user_id'], unique=False)
    op.create_index(op.f('ix_user_contacts_owner_user_id'), 'user_contacts', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_user_contacts_phone'), 'user_contacts', ['phone'], unique=False)
    op.create_table('message_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_id', 'chat_id'], ['messages.id', 'messages.chat_id'], name='fk_message_entity_message'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_entities_message_id_chat_id', 'message_entities', ['message_id', 'chat_id'], unique=False)
    op.create_index(op.f('ix_message_entities_type'), 'message_entities', ['type'], unique=False)
    op.create_table('message_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_id', 'chat_id'], ['messages.id', 'messages.chat_id'], name='fk_message_file_message'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_files_file_type'), 'message_files', ['file_type'], unique=False)
    op.create_index('ix_message_files_message_id_chat_id', 'message_files', ['message_id', 'chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_files_message_id_chat_id', table_name='message_files')
    op.drop_index(op.f('ix_message_files_file_type'), table_name='message_files')
    op.drop_table('message_files')
    op.drop_index(op.f('ix_message_entities_type'), table_name='message_entities')
    op.drop_index('ix_message_entities_message_id_chat_id', table_name='message_entities')
    op.drop_table('message_entities')
    op.drop_index(op.f('ix_user_contacts_phone'), table_name='user_contacts')
    op.drop_index(op.f('ix_user_contacts_owner_user_id'), table_name='user_contacts')
    op.drop_index(op.f('ix_user_contacts_contact_user_id'), table_name='user_contacts')
    op.drop_table('user_contacts')
    op.drop_index('ix_private_messages_dialog_date', table_name='private_messages')
    op.drop_index(op.f('ix_private_messages_date'), table_name='private_messages')
    op.drop_table('private_messages')
    op.drop_index('ix_messages_user_id', table_name='messages')
    op.drop_index(op.f('ix_messages_message_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_date'), table_name='messages')
    op.drop_index('ix_messages_chat_id_date', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_chat_participants_user_id', table_name='chat_participants')
    op.drop_index('ix_chat_participants_chat_id', table_name='chat_participants')
    op.drop_table('chat_participants')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_target_chats_username'), table_name='target_chats')
    op.drop_index(op.f('ix_target_chats_status'), table_name='target_chats')
    op.drop_index(op.f('ix_target_chats_chat_id'), table_name='target_chats')
    op.drop_table('target_chats')
    op.drop_table('app_users')
    # ### end Alembic commands ###
